In [1]:
import numpy as np
import pandas as pd
import tensorflow_recommenders as tfrs
import tensorflow as tf
from typing import Dict, Text

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [2]:
import pathlib
import os

user_file = "\\Data\\Combined Data.csv"
caregiver_file = "\\Data\\Processed Caregiver Data.csv"

path = pathlib.Path().resolve()
parent_path = path.parent.absolute()

user_dataframe = pd.read_csv(str(parent_path) + user_file)
caregiver_dataframe = pd.read_csv(str(parent_path) + caregiver_file)



In [3]:
unique_masalah_user = np.unique(' '.join(user_dataframe['Tipe_Masalah']).split(' '))
unique_masalah_caregiver = np.unique(' '.join(user_dataframe['Caregiver_Tipe_Masalah']).split(' '))
np.delete(unique_masalah_caregiver, np.where(unique_masalah_caregiver == ''))
unique_masalah_caregiver = np.delete(unique_masalah_caregiver, 0)

unique_masalah_caregiver = unique_masalah_caregiver.tolist()

for index, col in enumerate(unique_masalah_caregiver):
        unique_masalah_caregiver[index] = 'Caregiver-'+col


In [4]:
def convert_categorical_data(df, col='Tipe_Masalah'):
    ### Join every string in every row, split the result, pull out the unique values.
    genres = np.unique(' '.join(df[col]).split(' '))
    ### Drop 'NA'
    genres = np.delete(genres, np.where(genres == ''))
    if(col=='Tipe_Masalah'):
        for genre in genres:
            df[genre] = df[col].str.contains(genre).astype('int')
    else:
        for genre in genres:
            df['Caregiver-'+genre] = df[col].str.contains(genre).astype('int')
    df.drop(col, axis=1, inplace=True)

In [5]:
convert_categorical_data(user_dataframe)
convert_categorical_data(user_dataframe, col='Caregiver_Tipe_Masalah')
convert_categorical_data(caregiver_dataframe, col='Caregiver_Tipe_Masalah')


user_dataframe.drop(["USER_ID"], 1,inplace=True)
user_dataframe.drop(["CAREGIVER_ID"], 1,inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13900\1340759235.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  user_dataframe.drop(["USER_ID"], 1,inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13900\1340759235.py:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  user_dataframe.drop(["CAREGIVER_ID"], 1,inplace=True)


In [6]:

user_dataframe.head()



Gender  Age Caregiver_Gender  Caregiver_Age  \
0       Pria   33             Pria             19   
1       Pria   33             Pria             35   
2       Pria   29        Perempuan             33   
3       Pria   29             Pria             38   
4  Perempuan   32             Pria             35   

   ADHD-Hiperaktif-dan-kurang-fokus  Depresi  Gangguan-kecemasan  \
0                                 1        0                   0   
1                                 1        0                   0   
2                                 0        0                   0   
3                                 0        0                   0   
4                                 1        0                   1   

   Gangguan-makan  Gangguan-stres-pascatrauma  Skizofrenia  \
0               0                           0            0   
1               0                           0            0   
2               1                           1            0   
3               1                           1            0   
4               0                           0            0   

   Caregiver-ADHD-Hiperaktif-dan-kurang-fokus  Caregiver-Depresi  \
0                                           1                  0   
1                                           1                  0   
2                                           0                  0   
3                                           1                  0   
4                                           1                  0   

   Caregiver-Gangguan-kecemasan  Caregiver-Gangguan-makan  \
0                             0                         0   
1                             1                         0   
2                             0                         1   
3                             0                         1   
4                             1                         0   

   Caregiver-Gangguan-stres-pascatrauma  Caregiver-Skizofrenia  
0                                     0                      0  
1                                     1                      0  
2                                     1                      0  
3                                     0                      0  
4                                     1                      0

In [7]:

caregiver_dataframe.head()

CAREGIVER_ID Caregiver_Gender  Caregiver_Age  \
0             1        Perempuan             28   
1             2             Pria             33   
2             3             Pria             19   
3             4        Perempuan             18   
4             5        Perempuan             36   

   Caregiver-ADHD-Hiperaktif-dan-kurang-fokus  Caregiver-Depresi  \
0                                           1                  0   
1                                           0                  1   
2                                           1                  0   
3                                           0                  0   
4                                           0                  0   

   Caregiver-Gangguan-kecemasan  Caregiver-Gangguan-makan  \
0                             0                         1   
1                             0                         0   
2                             0                         0   
3                             0                         1   
4                             1                         0   

   Caregiver-Gangguan-stres-pascatrauma  Caregiver-Skizofrenia  
0                                     1                      0  
1                                     0                      1  
2                                     0                      0  
3                                     0                      1  
4                                     0                      1

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  ds = tf.data.Dataset.from_tensor_slices(dict(dataframe))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5# A small batch sized is used for demonstration purposes
caregiver_ds = df_to_dataset(caregiver_dataframe, batch_size=batch_size,  shuffle=False)
user_ds = df_to_dataset(user_dataframe, batch_size=batch_size)

In [10]:
feature_columns = []

number_feature = ["Age"]
number_feature += unique_masalah_user.tolist()
print(unique_masalah_caregiver)
# numeric cols
for header in number_feature:
    feature_columns.append(feature_column.numeric_column(header))

age_feature = ["Age"]
for col in age_feature:
    age = feature_column.numeric_column(col)
    age_buckets = feature_column.bucketized_column(age, boundaries=[17, 21, 25, 29, 33, 37, 41, 46])
    feature_columns.append(age_buckets)

['Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']


In [11]:
# indicator_columns
indicator_column_names = ['Gender']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, user_dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)



In [12]:
for col in feature_columns:
    print(col)

NumericColumn(key='Age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='ADHD-Hiperaktif-dan-kurang-fokus', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='Depresi', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='Gangguan-kecemasan', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='Gangguan-makan', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='Gangguan-stres-pascatrauma', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
NumericColumn(key='Skizofrenia', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)
BucketizedColumn(source_column=NumericColumn(key='Age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(17, 21, 25, 29, 33, 37, 41, 46))
IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='G

In [13]:
feature_layer_user= tf.keras.layers.DenseFeatures(feature_columns)

In [14]:
feature_columns = []

number_feature = ["Caregiver_Age"]
number_feature += unique_masalah_caregiver
print(unique_masalah_caregiver)
# numeric cols

for header in number_feature:
    feature_columns.append(feature_column.numeric_column(header))

age_feature = ["Caregiver_Age"]
for col in age_feature:
    age = feature_column.numeric_column(col)
    age_buckets = feature_column.bucketized_column(age, boundaries=[17, 21, 25, 29, 33, 37, 41, 46])
    feature_columns.append(age_buckets)

col_name = 'Caregiver_Gender'
categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, user_dataframe[col_name].unique())
indicator_column = feature_column.indicator_column(categorical_column)
feature_columns.append(indicator_column)

['Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']


In [15]:
feature_layer_caregiver= tf.keras.layers.DenseFeatures(feature_columns)

In [16]:
class RecomendModel(tfrs.Model):

  def __init__(self):
    super().__init__()

    embedding_dimension = 32

    # Set up a model for representing users.
    self.user_model = tf.keras.Sequential([
        feature_layer_user,
        layers.Dense(64),
        layers.Dense(32)
    ])

    # Set up a model for representing caregiver.
    self.caregiver_model = tf.keras.Sequential([
        feature_layer_caregiver,
        layers.Dense(64),
        layers.Dense(32)
    ])

    # Set up a task to optimize the model and compute metrics.
    self.task = tfrs.tasks.Retrieval(
      metrics=tfrs.metrics.FactorizedTopK(
        candidates=caregiver_ds.batch(5).map(self.caregiver_model)
      )
    )

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    
    caregiver_features = ['Caregiver_Gender', 'Caregiver_Age',  'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']
    user_features = ['Gender', 'Age', 'ADHD-Hiperaktif-dan-kurang-fokus', 'Depresi', 'Gangguan-kecemasan', 'Gangguan-makan','Gangguan-stres-pascatrauma', 'Skizofrenia']
    
    
    # We pick out the user features and pass them into the user model.
    
    print("AAAAAAAAAAAAAAAAAA")
    user_embeddings = self.user_model({
        'Age':features['Age'],
        'Gender':features['Gender'],
        'ADHD-Hiperaktif-dan-kurang-fokus':features['ADHD-Hiperaktif-dan-kurang-fokus'],
        'Depresi':features['Depresi'],
        'Gangguan-kecemasan':features['Gangguan-kecemasan'],
        'Gangguan-makan':features['Gangguan-makan'],
        'Gangguan-stres-pascatrauma':features['Gangguan-stres-pascatrauma'],
        'Skizofrenia':features['Skizofrenia']
    })
    print("BBBBBBBBBBBBBB")
    # And pick out the movie features and pass them into the movie model,
    # getting embeddings back.
    positive_movie_embeddings = self.caregiver_model({
        'Caregiver_Age':features['Caregiver_Age'],
        'Caregiver_Gender':features['Caregiver_Gender'],
        'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus':features['Caregiver-ADHD-Hiperaktif-dan-kurang-fokus'],
        'Caregiver-Depresi':features['Caregiver-Depresi'],
        'Caregiver-Gangguan-kecemasan':features['Caregiver-Gangguan-kecemasan'],
        'Caregiver-Gangguan-makan':features['Caregiver-Gangguan-makan'],
        'Caregiver-Gangguan-stres-pascatrauma':features['Caregiver-Gangguan-stres-pascatrauma'],
        'Caregiver-Skizofrenia':features['Caregiver-Skizofrenia']
        
    })
    

    # The task computes the loss and the metrics.

    return self.task(user_embeddings, positive_movie_embeddings, compute_metrics=not training)

In [17]:
caregiver_features = ['Caregiver_Gender', 'Caregiver_Age',  'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']
user_features = ['Gender', 'Age', 'ADHD-Hiperaktif-dan-kurang-fokus', 'Depresi', 'Gangguan-kecemasan', 'Gangguan-makan','Gangguan-stres-pascatrauma', 'Skizofrenia']

In [18]:

for feature_batch in caregiver_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Caregiver-ADHD-Hiperaktif-dan-kurang-fokus'])

Every feature: ['CAREGIVER_ID', 'Caregiver_Gender', 'Caregiver_Age', 'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']
A batch of ages: tf.Tensor([1 0 1 0 0], shape=(5,), dtype=int32)


In [19]:
model = RecomendModel()

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit(user_ds,
          epochs=50)

Epoch 1/50
AAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBB
40/40 [==============================] - 2s 7ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 84.1777 - regularization_loss: 0.0000e+00 - total_loss: 84.1777
Epoch 2/50
40/40 [==============================] - 0s 7ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 20.4741 - regularization_loss: 0.0000e+00 - total_loss: 20.4741
Epoch 3/50
40/40 [==============================] - 0s 7ms/step - factor

40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 8.6093 - regularization_loss: 0.0000e+00 - total_loss: 8.6093
Epoch 11/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 8.6342 - regularization_loss: 0.0000e+00 - total_loss: 8.6342
Epoch 12/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_catego

40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 7.3609 - regularization_loss: 0.0000e+00 - total_loss: 7.3609
Epoch 30/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 7.0016 - regularization_loss: 0.0000e+00 - total_loss: 7.0016
Epoch 31/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_catego

40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 6.4783 - regularization_loss: 0.0000e+00 - total_loss: 6.4783
Epoch 49/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: 6.6240 - regularization_loss: 0.0000e+00 - total_loss: 6.6240
Epoch 50/50
40/40 [==============================] - 0s 8ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_catego

In [20]:
for feature_batch in caregiver_ds:
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch)

Every feature: ['CAREGIVER_ID', 'Caregiver_Gender', 'Caregiver_Age', 'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus', 'Caregiver-Depresi', 'Caregiver-Gangguan-kecemasan', 'Caregiver-Gangguan-makan', 'Caregiver-Gangguan-stres-pascatrauma', 'Caregiver-Skizofrenia']
A batch of ages: {'CAREGIVER_ID': <tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5], dtype=int64)>, 'Caregiver_Gender': <tf.Tensor: shape=(5,), dtype=string, numpy=
array([b'Perempuan', b'Pria', b'Pria', b'Perempuan', b'Perempuan'],
      dtype=object)>, 'Caregiver_Age': <tf.Tensor: shape=(5,), dtype=int64, numpy=array([28, 33, 19, 18, 36], dtype=int64)>, 'Caregiver-ADHD-Hiperaktif-dan-kurang-fokus': <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 0, 1, 0, 0])>, 'Caregiver-Depresi': <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 0, 0])>, 'Caregiver-Gangguan-kecemasan': <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 1])>, 'Caregiver-Gangguan-makan': <tf.Tensor: shape=(5,), dtype=int32

In [31]:
brute_force = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
brute_force.index_from_dataset(  
       caregiver_ds.map(lambda features: (features['CAREGIVER_ID'], model.caregiver_model(features)))
)





In [22]:
a =['Gender', 'Age', 'ADHD-Hiperaktif-dan-kurang-fokus', 'Depresi', 'Gangguan-kecemasan', 'Gangguan-makan','Gangguan-stres-pascatrauma', 'Skizofrenia']
value = ['Pria', 30, 0, 1, 0, 0, 1, 0]
dictionary_Test = dict((el,np.array([value[ix]])) for ix,el in enumerate(a))
print(dictionary_Test)

{'Gender': array(['Pria'], dtype='<U4'), 'Age': array([30]), 'ADHD-Hiperaktif-dan-kurang-fokus': array([0]), 'Depresi': array([1]), 'Gangguan-kecemasan': array([0]), 'Gangguan-makan': array([0]), 'Gangguan-stres-pascatrauma': array([1]), 'Skizofrenia': array([0])}


In [23]:
# Get predictions for user 42.
a, titles = brute_force(dictionary_Test, k=2)
print(f"Top recommendations: {titles[0]}")

Top recommendations: [17 11]


In [25]:
tensor = model.user_model(dictionary_Test)
tensor.numpy()

array([[ 0.07992546,  0.04781152, -0.3413666 , -1.2493048 ,  0.50396305,
         0.6881075 ,  0.55912286, -1.15427   ,  0.1509069 ,  1.337718  ,
        -0.45005974,  3.1346717 ,  0.26507953,  0.12471665, -1.0504792 ,
        -0.44568485,  1.4500772 ,  1.8927057 ,  0.0526594 , -0.95920485,
        -0.09666137, -2.2241206 ,  2.7120328 ,  0.30885193,  0.33919173,
         1.2163811 , -1.7750607 , -1.0678444 ,  0.435505  , -0.07476552,
        -0.6076032 ,  0.7087519 ]], dtype=float32)

In [26]:
processed_ds = caregiver_ds.batch(5).map(model.caregiver_model)


In [27]:
model.save

<bound method Model.save of <__main__.RecomendModel object at 0x000001975DC0C0A0>>

In [28]:
processed_ds

<MapDataset element_spec=TensorSpec(shape=(None, 32), dtype=tf.float32, name=None)>

In [29]:
tf.saved_model.save(model.user_model, 'saved_model/user_query_v1')

INFO:tensorflow:Assets written to: saved_model/user_query_v1\assets


INFO:tensorflow:Assets written to: saved_model/user_query_v1\assets


In [30]:
tf.saved_model.save(model.caregiver_model, 'saved_model/caregiver_query_v1')

INFO:tensorflow:Assets written to: saved_model/caregiver_query_v1\assets


INFO:tensorflow:Assets written to: saved_model/caregiver_query_v1\assets
